### ISSUE TITLE
crashes on macOS Sierra version 10.12.2

### ISSUE THREAD

**Issue by chujian** [codestation/qcma#85]
Process:               qcma [6510]
Path:                  /Applications/Qcma.app/Contents/MacOS/qcma
Identifier:            com.yourcompany.qcma
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           qcma [6510]
User ID:               501

Date/Time:             2017-01-08 19:32:15.186 +0800
OS Version:            Mac OS X 10.12.2 (16C67)
Report Version:        12
Anonymous UUID:        5A36F262-675E-7EE8-FDE0-EA1DCDA16653

Time Awake Since Boot: 87000 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/Cellar/ffmpeg/3.2/lib/libavcodec.57.dylib
  Referenced from: /Applications/Qcma.app/Contents/Frameworks/libavformat.57.dylib
  Reason: image not found

Binary Images:
       0x10f111000 -        0x10f183fff +com.yourcompany.qcma (0) <4B1A696B-53C7-3486-AD5F-78A1B051796C> /Applications/Qcma.app/Contents/MacOS/qcma
       0x10f1b4000 -        0x10f1d6ff7 +libvitamtp.5.dylib (0) <E160526C-18C7-3530-8432-FA9E2181B211> /Applications/Qcma.app/Contents/Frameworks/libvitamtp.5.dylib
       0x10f1e6000 -        0x10f34fff7 +libavformat.57.dylib (0) <704AF7AC-27A2-338B-A405-162D6B4FB982> /Applications/Qcma.app/Contents/Frameworks/libavformat.57.dylib
       0x10f394000 -        0x10ffa8ff7 +libavcodec.57.dylib (0) <9BBE06FB-F5AA-36DE-8097-CA95F41A54BB> /Applications/Qcma.app/Contents/Frameworks/libavcodec.57.dylib
       0x11059a000 -        0x1105dcff7 +libavutil.55.dylib (0) <4CCD1069-B8C3-3326-9059-4D4FE62CF11D> /Applications/Qcma.app/Contents/Frameworks/libavutil.55.dylib
       0x110605000 -        0x11067bfff +libswscale.4.dylib (0) <74A239CD-0519-3C02-9CB5-1F430353372C> /Applications/Qcma.app/Contents/Frameworks/libswscale.4.dylib
       0x110689000 -        0x110b82ff7 +org.qt-project.QtWidgets (5.7 - 5.7.0) <9029D91F-7F7E-3DE0-BD66-FC91DD8112C3> /Applications/Qcma.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x110ce1000 -        0x111141ff7 +org.qt-project.QtGui (5.7 - 5.7.0) <A41CBDE5-2955-3A57-BAE9-69001B210588> /Applications/Qcma.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x111234000 -        0x111748ff7 +org.qt-project.QtCore (5.7 - 5.7.0) <5F2F454C-CEE8-3E59-A3B7-94F51F5B9F96> /Applications/Qcma.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x1117fc000 -        0x111900ff7 +org.qt-project.QtNetwork (5.7 - 5.7.0) <B40B02F2-BD1A-3593-831A-6E9C83FA1D61> /Applications/Qcma.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x111940000 -        0x11196afff +org.qt-project.QtSql (5.7 - 5.7.0) <071A7940-CCF2-3B88-A7E2-AB520B73DD40> /Applications/Qcma.app/Contents/Frameworks/QtSql.framework/Versions/5/QtSql
       0x11197e000 -        0x111982ffb  com.apple.agl (3.3.1 - AGL-3.3.1) <E4A1E7B9-9C37-3244-8415-F0F028CB2859> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
       0x11198f000 -        0x111a7ffff +libxml2.2.dylib (0) <2452DC63-673D-361E-BEB7-90091006445A> /Applications/Qcma.app/Contents/Frameworks/libxml2.2.dylib
       0x111aae000 -        0x111abdfff +libusb-1.0.0.dylib (0) <24074467-ED01-338E-BE4D-1C0D9DDC84A9> /Applications/Qcma.app/Contents/Frameworks/libusb-1.0.0.dylib
       0x114ec7000 -        0x114f04267  dyld (421.2) <947FC440-80F9-32F7-A773-6FC418FE1AB7> /usr/lib/dyld
    0x7fffd24e5000 -     0x7fffd2979ff7  com.apple.CoreFoundation (6.9 - 1348.28) <0F1FAA52-1C06-327E-A170-382B48B1846D> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fffd3de6000 -     0x7fffd3debfff  com.apple.DiskArbitration (2.7 - 2.7) <16EA6D93-A2EC-31DB-BF52-C4764E7B1630> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fffd44e2000 -     0x7fffd4577ff7  com.apple.framework.IOKit (2.0.2 - 1324.30.13) <163BE7FA-B29A-348F-8B5F-E301F2E8C964> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fffd757d000 -     0x7fffd758bfff  com.apple.opengl (13.0.10 - 13.0.10) <7F1E35F8-F0D1-389B-B8CC-E06E02714005> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fffe630e000 -     0x7fffe630fff3  libDiagnosticMessagesClient.dylib (102) <422911A4-E273-3E88-BFC4-DF6470E48242> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fffe654d000 -     0x7fffe654eff3  libSystem.B.dylib (1238) <FF55E335-37C3-3567-9415-A3A1473775F5> /usr/lib/libSystem.B.dylib
    0x7fffe66df000 -     0x7fffe66dfff3  libauto.dylib (187) <5BBF6A00-CC76-389D-84E7-CA88EDADE683> /usr/lib/libauto.dylib
    0x7fffe66e0000 -     0x7fffe66f0ff3  libbsm.0.dylib (34) <20084796-B04D-3B35-A003-EA11459557A9> /usr/lib/libbsm.0.dylib
    0x7fffe6700000 -     0x7fffe6756ff7  libc++.1.dylib (307.4) <BEE86868-F831-384C-919E-2B286ACFE87C> /usr/lib/libc++.1.dylib
    0x7fffe6757000 -     0x7fffe6781fff  libc++abi.dylib (307.2) <1CEF8ABB-7E6D-3C2F-8E0A-E7884478DD23> /usr/lib/libc++abi.dylib
    0x7fffe6bb6000 -     0x7fffe6bb6fff  libenergytrace.dylib (15) <A1B040A2-7977-3097-9ADF-34FF181EB970> /usr/lib/libenergytrace.dylib
    0x7fffe6bcc000 -     0x7fffe6cbeff7  libiconv.2.dylib (50) <42125B35-81D7-3FC4-9475-A26DBE10884D> /usr/lib/libiconv.2.dylib
    0x7fffe6cbf000 -     0x7fffe6ee4ffb  libicucore.A.dylib (57149.0.1) <6B5FDA93-AA88-318F-9608-C2A33D602EC7> /usr/lib/libicucore.A.dylib
    0x7fffe7271000 -     0x7fffe7646127  libobjc.A.dylib (706) <47104A1B-13E8-369F-BC36-27FF465809FD> /usr/lib/libobjc.A.dylib
    0x7fffe7a69000 -     0x7fffe7a7aff3  libz.1.dylib (67) <46E3FFA2-4328-327A-8D34-A03E20BFFB8E> /usr/lib/libz.1.dylib
    0x7fffe7a89000 -     0x7fffe7a8dff7  libcache.dylib (79) <0C8092D3-600F-3ADD-A036-F225B6CDCA43> /usr/lib/system/libcache.dylib
    0x7fffe7a8e000 -     0x7fffe7a99ff7  libcommonCrypto.dylib (60092.30.2) <B16E29B6-EC8D-3A8F-9A89-DD9CF35F7C4B> /usr/lib/system/libcommonCrypto.dylib
    0x7fffe7a9a000 -     0x7fffe7aa1fff  libcompiler_rt.dylib (62) <E992E8D9-037C-3454-A366-A25E4D31D6BB> /usr/lib/system/libcompiler_rt.dylib
    0x7fffe7aa2000 -     0x7fffe7aaafff  libcopyfile.dylib (138) <64E285D9-5485-333B-AEE7-8B0C8FB9275F> /usr/lib/system/libcopyfile.dylib
    0x7fffe7aab000 -     0x7fffe7b2efdf  libcorecrypto.dylib (442.30.20) <2074B932-FD79-30A9-8E90-AF25C49F2AF1> /usr/lib/system/libcorecrypto.dylib
    0x7fffe7b2f000 -     0x7fffe7b61fff  libdispatch.dylib (703.30.5) <EA0CC14E-D559-3802-B4B2-0E8C7579AAC4> /usr/lib/system/libdispatch.dylib
    0x7fffe7b62000 -     0x7fffe7b67ff3  libdyld.dylib (421.2) <E5A2414F-2480-3BB2-BE94-176119A80876> /usr/lib/system/libdyld.dylib
    0x7fffe7b68000 -     0x7fffe7b68ffb  libkeymgr.dylib (28) <1A318923-1200-3B06-B432-5007D82F195D> /usr/lib/system/libkeymgr.dylib
    0x7fffe7b69000 -     0x7fffe7b75ffb  libkxld.dylib (3789.31.2) <524D7C3D-73EB-3F62-ADB1-9DFBACB95924> /usr/lib/system/libkxld.dylib
    0x7fffe7b76000 -     0x7fffe7b76fff  liblaunch.dylib (972.30.7) <15FACC21-079A-3BDF-9AFB-4253EFDEB587> /usr/lib/system/liblaunch.dylib
    0x7fffe7b77000 -     0x7fffe7b7cfff  libmacho.dylib (894) <A2F38EC1-C37C-3B93-B0E4-36B07C177F8C> /usr/lib/system/libmacho.dylib
    0x7fffe7b7d000 -     0x7fffe7b7fff3  libquarantine.dylib (85) <C1D7749F-5F5F-3BB9-BEFC-1F0B9DA941FD> /usr/lib/system/libquarantine.dylib
    0x7fffe7b80000 -     0x7fffe7b81ffb  libremovefile.dylib (45) <CD42974E-BE0B-39FC-9BFC-8A7540A04DC6> /usr/lib/system/libremovefile.dylib
    0x7fffe7b82000 -     0x7fffe7b9aff7  libsystem_asl.dylib (349.30.2) <EFAC72D7-CB13-3DF7-ADF3-EC6635C6F1EA> /usr/lib/system/libsystem_asl.dylib
    0x7fffe7b9b000 -     0x7fffe7b9bff7  libsystem_blocks.dylib (67) <B8C3701D-5A91-3D35-999D-2DC8D5393525> /usr/lib/system/libsystem_blocks.dylib
    0x7fffe7b9c000 -     0x7fffe7c29fef  libsystem_c.dylib (1158.30.7) <2F881962-03CB-3B9D-A782-D98C1BBA4E3D> /usr/lib/system/libsystem_c.dylib
    0x7fffe7c2a000 -     0x7fffe7c2dffb  libsystem_configuration.dylib (888.30.2) <4FE3983C-E4ED-3939-A578-03AD29C99788> /usr/lib/system/libsystem_configuration.dylib
    0x7fffe7c2e000 -     0x7fffe7c31fff  libsystem_coreservices.dylib (41.4) <1A572B9E-0C47-320F-8C64-7990D0A5FB5A> /usr/lib/system/libsystem_coreservices.dylib
    0x7fffe7c32000 -     0x7fffe7c4aff3  libsystem_coretls.dylib (121.31.1) <4676F06D-274D-31BE-B61C-4D7A4AEF4858> /usr/lib/system/libsystem_coretls.dylib
    0x7fffe7c4b000 -     0x7fffe7c51fff  libsystem_dnssd.dylib (765.30.11) <DC708D84-ED7D-3936-B996-A67C66B8DDAA> /usr/lib/system/libsystem_dnssd.dylib
    0x7fffe7c52000 -     0x7fffe7c7bff7  libsystem_info.dylib (503.30.1) <9ED9121C-F111-3FAD-BC2F-C95DEE1C9362> /usr/lib/system/libsystem_info.dylib
    0x7fffe7c7c000 -     0x7fffe7c9eff7  libsystem_kernel.dylib (3789.31.2) <FCEEBBD4-DF66-34D8-A32F-4F8C8E814E40> /usr/lib/system/libsystem_kernel.dylib
    0x7fffe7c9f000 -     0x7fffe7ce6fe7  libsystem_m.dylib (3121.4) <266DB92B-A86F-3691-80FB-1B26AD73CFF3> /usr/lib/system/libsystem_m.dylib
    0x7fffe7ce7000 -     0x7fffe7d05ff7  libsystem_malloc.dylib (116.30.3) <F40DEE3B-386A-3529-A3F7-98117ED55BF4> /usr/lib/system/libsystem_malloc.dylib
    0x7fffe7d06000 -     0x7fffe7d5dffb  libsystem_network.dylib (856.30.16) <4AE368E9-605D-379D-B04C-2AC7455B8250> /usr/lib/system/libsystem_network.dylib
    0x7fffe7d5e000 -     0x7fffe7d67ff3  libsystem_networkextension.dylib (563.30.15) <EB020B0C-7DF0-3EEF-8E3C-15DA3C01D687> /usr/lib/system/libsystem_networkextension.dylib
    0x7fffe7d68000 -     0x7fffe7d71ff3  libsystem_notify.dylib (165.20.1) <E7FD3A7C-DD07-36E2-9FA4-7561F9F114DA> /usr/lib/system/libsystem_notify.dylib
    0x7fffe7d72000 -     0x7fffe7d7afe7  libsystem_platform.dylib (126.1.2) <3CA06D4E-C00A-36DE-AA65-3A390097D1F6> /usr/lib/system/libsystem_platform.dylib
    0x7fffe7d7b000 -     0x7fffe7d85ff7  libsystem_pthread.dylib (218.30.1) <C869ED7C-BE29-3532-8E69-3A8DA1447EDC> /usr/lib/system/libsystem_pthread.dylib
    0x7fffe7d86000 -     0x7fffe7d89ff7  libsystem_sandbox.dylib (592.31.1) <7BBFDF96-293F-3DD9-B3A4-7C168280B441> /usr/lib/system/libsystem_sandbox.dylib
    0x7fffe7d8a000 -     0x7fffe7d8bfff  libsystem_secinit.dylib (24) <5C1F1E47-0F7D-3E25-8DEB-D9DB1F902281> /usr/lib/system/libsystem_secinit.dylib
    0x7fffe7d8c000 -     0x7fffe7d93fff  libsystem_symptoms.dylib (532.30.6) <5D990CF5-B58F-39F7-B375-99B4EC62CFBD> /usr/lib/system/libsystem_symptoms.dylib
    0x7fffe7d94000 -     0x7fffe7db4ff7  libsystem_trace.dylib (518.30.7) <5BD4ECD4-75CA-38EA-AF5C-B481C15955F8> /usr/lib/system/libsystem_trace.dylib
    0x7fffe7db5000 -     0x7fffe7dbaffb  libunwind.dylib (35.3) <9F7C2AD8-A9A7-3DE4-828D-B0F0F166AAA0> /usr/lib/system/libunwind.dylib
    0x7fffe7dbb000 -     0x7fffe7de4ff7  libxpc.dylib (972.30.7) <65E41BB6-EBD5-3D93-B0BE-B190CEE4DD93> /usr/lib/system/libxpc.dylib

Model: Macmini6,2, BootROM MM61.0106.B0B, 4 processors, Intel Core i7, 2.3 GHz, 10 GB, SMC 2.8f0
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54333235533643465238432D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x0198, 0x393930353432382D3432372E4130304C4620
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x10E), Broadcom BCM43xx 1.0 (7.21.171.68.1a4)
Bluetooth: Version 5.0.2f4, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: OCZ-TRION150, 240.06 GB
Serial ATA Device: APPLE HDD HTS541010A9E662, 1 TB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: USB 3.0 Bus
USB Device: USB3.0 Hub
USB Device: USB2.0 Hub
USB Device: Mass Storage
USB Device: "PS Vita" Type B
Thunderbolt Bus: Mac mini, Apple Inc., 23.4

**Comment by chujian** [comment]
The problem is solved,the program is missing ffmpeg

 brew install ffmpeg

**Comment by hexxellor** [comment]
I don't know that this is really resolved. There are two versions listed on here one without ffmpeg and one with it. Installing the version without it works for me (I have ffmpeg already installed via homebrew), however, installing the one that says it includes it does NOT work. That one gives the error above on the same OS version. Maybe some others should check it out in case I have something messed up in my setup but this just recently happened although I'm not sure exactly when. Prior to that 0.4.1 worked on my machine.... so that's the strange part.

**Comment by Dochartaigh** [comment]
Not fixed for me either. 10.12.2. Tried both a 2014 MacBook Air, and a 2012 Mac Mini. Tried both versions of QCMA. "brew install ffmpeg" gives me a "command not found error"....even the terminal command to install brew on their own site doesn't work...

**Comment by Dochartaigh** [comment]
Just an update in case this helps anybody - this WILL work on Sierra but you have to install homebrew FIRST before running the "brew install ffmpeg" command above. To install Homebrew, on your mac, in Terminal type:

```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

**Comment by StephDC** [comment]
What if I have a ffmpeg installed through MacPorts or downloaded from http://evermeet.cx/ffmpeg/ ?

**Comment by renanmd** [comment]
Dochartaigh, you rock! your post helped me make my qmca run. tks!

**Comment by ccfman2004** [comment]
This worked for me.  10.13.3

**Comment by t0mtaylor** [comment]
👍

**Comment by annanen** [comment]
Hi,

I did both but not working.
`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

`brew install ffmpeg`

And this is the report

Process:               qcma [2164]
Path:                  /Applications/Qcma.app/Contents/MacOS/qcma
Identifier:            com.yourcompany.qcma
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           qcma [2164]
User ID:               501

Date/Time:             2018-07-06 10:20:05.166 +0300
OS Version:            Mac OS X 10.13.5 (17F77)
Report Version:        12
Anonymous UUID:        35280B53-EABE-12BD-C798-69CA7DE797C5


Time Awake Since Boot: 5900 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/Cellar/ffmpeg/3.2/lib/libavcodec.57.dylib
  Referenced from: /Applications/Qcma.app/Contents/Frameworks/libavformat.57.dylib
  Reason: image not found

Binary Images:
       0x107404000 -        0x107476fff +com.yourcompany.qcma (0) <4B1A696B-53C7-3486-AD5F-78A1B051796C> /Applications/Qcma.app/Contents/MacOS/qcma
       0x1074a1000 -        0x1074c3ff7 +libvitamtp.5.dylib (0) <E160526C-18C7-3530-8432-FA9E2181B211> /Applications/Qcma.app/Contents/Frameworks/libvitamtp.5.dylib
       0x1074ce000 -        0x107637ff7 +libavformat.57.dylib (0) <704AF7AC-27A2-338B-A405-162D6B4FB982> /Applications/Qcma.app/Contents/Frameworks/libavformat.57.dylib
       0x107675000 -        0x1076b7ff7 +libavutil.55.dylib (0) <4CCD1069-B8C3-3326-9059-4D4FE62CF11D> /Applications/Qcma.app/Contents/Frameworks/libavutil.55.dylib
       0x1076d9000 -        0x10774ffff +libswscale.4.dylib (0) <74A239CD-0519-3C02-9CB5-1F430353372C> /Applications/Qcma.app/Contents/Frameworks/libswscale.4.dylib
       0x10775c000 -        0x107c55ff7 +org.qt-project.QtWidgets (5.7 - 5.7.0) <9029D91F-7F7E-3DE0-BD66-FC91DD8112C3> /Applications/Qcma.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x107db0000 -        0x107eb4ff7 +org.qt-project.QtNetwork (5.7 - 5.7.0) <B40B02F2-BD1A-3593-831A-6E9C83FA1D61> /Applications/Qcma.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x107ef4000 -        0x107f1efff +org.qt-project.QtSql (5.7 - 5.7.0) <071A7940-CCF2-3B88-A7E2-AB520B73DD40> /Applications/Qcma.app/Contents/Frameworks/QtSql.framework/Versions/5/QtSql
       0x107f31000 -        0x108021fff +libxml2.2.dylib (0) <2452DC63-673D-361E-BEB7-90091006445A> /Applications/Qcma.app/Contents/Frameworks/libxml2.2.dylib
       0x108049000 -        0x108058fff +libusb-1.0.0.dylib (0) <24074467-ED01-338E-BE4D-1C0D9DDC84A9> /Applications/Qcma.app/Contents/Frameworks/libusb-1.0.0.dylib
       0x1080a5000 -        0x1080ef9df  dyld (551.3) <AFAB4EFA-7020-34B1-BBEF-0F26C6D3CA36> /usr/lib/dyld
       0x108143000 -        0x108d57ff7 +libavcodec.57.dylib (0) <9BBE06FB-F5AA-36DE-8097-CA95F41A54BB> /Applications/Qcma.app/Contents/Frameworks/libavcodec.57.dylib
       0x109349000 -        0x1097a9ff7 +org.qt-project.QtGui (5.7 - 5.7.0) <A41CBDE5-2955-3A57-BAE9-69001B210588> /Applications/Qcma.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x10989a000 -        0x109daeff7 +org.qt-project.QtCore (5.7 - 5.7.0) <5F2F454C-CEE8-3E59-A3B7-94F51F5B9F96> /Applications/Qcma.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
    0x7fff2487c000 -     0x7fff24880ffb  com.apple.agl (3.3.1 - AGL-3.3.1) <9452E8D8-F1F4-32B1-ACEB-7B2415A4F9D3> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff286aa000 -     0x7fff28b4bfef  com.apple.CoreFoundation (6.9 - 1452.23) <945E5C0A-86C5-336E-A64F-5BF06E78985A> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff2a645000 -     0x7fff2a64afff  com.apple.DiskArbitration (2.7 - 2.7) <B059E12C-94EA-3A39-A03F-8AAB5F4EE1F2> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff2aee7000 -     0x7fff2af82ff7  com.apple.framework.IOKit (2.0.2 - 1445.60.1) <7C16F358-1F63-349F-AD58-F7B287C7B7B7> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff32c22000 -     0x7fff32c31fff  com.apple.opengl (16.5.10 - 16.5.10) <D51C7DE3-ABE0-3CED-BB9C-7D71C3205FB6> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff4dd27000 -     0x7fff4dd5aff7  libclosured.dylib (551.3) <DC3DA678-9C40-339C-A9C6-32AB74FCC682> /usr/lib/closure/libclosured.dylib
    0x7fff4deeb000 -     0x7fff4deecff3  libDiagnosticMessagesClient.dylib (104) <9712E980-76EE-3A89-AEA6-DF4BAF5C0574> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff4e261000 -     0x7fff4e262ffb  libSystem.B.dylib (1252.50.4) <CDA73F3E-2A7D-3354-818A-580317A03255> /usr/lib/libSystem.B.dylib
    0x7fff4e477000 -     0x7fff4e487ff3  libbsm.0.dylib (39) <6BC96A72-AFBE-34FD-91B1-748A530D8AE6> /usr/lib/libbsm.0.dylib
    0x7fff4e496000 -     0x7fff4e4ecfff  libc++.1.dylib (400.9) <7D3DACCC-3804-393C-ABC1-1A580FD00CB6> /usr/lib/libc++.1.dylib
    0x7fff4e4ed000 -     0x7fff4e511ff7  libc++abi.dylib (400.8.2) <EF5E37D7-11D9-3530-BE45-B986612D13E2> /usr/lib/libc++abi.dylib
    0x7fff4ee67000 -     0x7fff4ee67fff  libenergytrace.dylib (16) <A92AB8B8-B986-3CE6-980D-D55090FEF387> /usr/lib/libenergytrace.dylib
    0x7fff4eecf000 -     0x7fff4efc0ff7  libiconv.2.dylib (51.50.1) <2FEC9707-3FAF-3828-A50D-8605086D060F> /usr/lib/libiconv.2.dylib
    0x7fff4efc1000 -     0x7fff4f1e8ffb  libicucore.A.dylib (59180.0.1) <49C253CB-1BEF-3FF6-ABAB-7BACEEDE8C94> /usr/lib/libicucore.A.dylib
    0x7fff4f919000 -     0x7fff4fd077e7  libobjc.A.dylib (723) <DD9E5EC5-B507-3249-B700-93433E2D5EDF> /usr/lib/libobjc.A.dylib
    0x7fff5032f000 -     0x7fff50341ffb  libz.1.dylib (70) <48C67CFC-940D-3857-8DAD-857774605352> /usr/lib/libz.1.dylib
    0x7fff503dd000 -     0x7fff503e1ff7  libcache.dylib (80) <092479CB-1008-3A83-BECF-E115F24D13C1> /usr/lib/system/libcache.dylib
    0x7fff503e2000 -     0x7fff503ecff3  libcommonCrypto.dylib (60118.50.1) <029F5985-9B6E-3DCB-9B96-FD007678C6A7> /usr/lib/system/libcommonCrypto.dylib
    0x7fff503ed000 -     0x7fff503f4fff  libcompiler_rt.dylib (62) <968B8E3F-3681-3230-9D78-BB8732024F6E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff503f5000 -     0x7fff503feffb  libcopyfile.dylib (146.50.5) <3885083D-50D8-3EEC-B481-B2E605180D7F> /usr/lib/system/libcopyfile.dylib
    0x7fff503ff000 -     0x7fff50484fff  libcorecrypto.dylib (562.50.17) <67007279-24E1-3F30-802D-A55CD5C27946> /usr/lib/system/libcorecrypto.dylib
    0x7fff5050c000 -     0x7fff50545ff7  libdispatch.dylib (913.60.2) <414353F7-3A9F-3091-AFCE-E66F74687D5D> /usr/lib/system/libdispatch.dylib
    0x7fff50546000 -     0x7fff50563ff7  libdyld.dylib (551.3) <CF59A5A5-288B-30E6-BD42-9056B4E4139A> /usr/lib/system/libdyld.dylib
    0x7fff50564000 -     0x7fff50564ffb  libkeymgr.dylib (28) <E34E283E-90FA-3C59-B48E-1277CDB9CDCE> /usr/lib/system/libkeymgr.dylib
    0x7fff50565000 -     0x7fff50571ff3  libkxld.dylib (4570.61.1) <E394563E-F5D5-338D-B733-445A553E6327> /usr/lib/system/libkxld.dylib
    0x7fff50572000 -     0x7fff50572ff7  liblaunch.dylib (1205.60.9) <4B2943A9-0994-3E8B-94B8-98DA9CED0021> /usr/lib/system/liblaunch.dylib
    0x7fff50573000 -     0x7fff50577ffb  libmacho.dylib (906) <1902A611-081A-3452-B11E-EBD1B166E831> /usr/lib/system/libmacho.dylib
    0x7fff50578000 -     0x7fff5057aff3  libquarantine.dylib (86) <26C0BA22-8F93-3A07-9A4E-C8D53D2CE42E> /usr/lib/system/libquarantine.dylib
    0x7fff5057b000 -     0x7fff5057cff3  libremovefile.dylib (45) <711E18B2-5BBE-3211-A916-56740C27D17A> /usr/lib/system/libremovefile.dylib
    0x7fff5057d000 -     0x7fff50594fff  libsystem_asl.dylib (356.50.1) <3B24F2D1-B578-359D-ADB2-0ED19A364C38> /usr/lib/system/libsystem_asl.dylib
    0x7fff50595000 -     0x7fff50595fff  libsystem_blocks.dylib (67) <17303FDF-0D2D-3963-B05E-B4DF63052D47> /usr/lib/system/libsystem_blocks.dylib
    0x7fff50596000 -     0x7fff5061fff7  libsystem_c.dylib (1244.50.9) <1187BFE8-4576-3247-8177-481554E1F9E7> /usr/lib/system/libsystem_c.dylib
    0x7fff50620000 -     0x7fff50623ffb  libsystem_configuration.dylib (963.50.8) <DF6B5287-203E-30CB-9947-78DF446C72B8> /usr/lib/system/libsystem_configuration.dylib
    0x7fff50624000 -     0x7fff50627ffb  libsystem_coreservices.dylib (51) <486000D3-D8CB-3BE7-8EE5-8BF380DE6DF7> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff50628000 -     0x7fff50629fff  libsystem_darwin.dylib (1244.50.9) <09C21A4A-9EE0-388B-A9D9-DFF8F6758791> /usr/lib/system/libsystem_darwin.dylib
    0x7fff5062a000 -     0x7fff50630ff7  libsystem_dnssd.dylib (878.50.17) <C12E2075-3E4B-3187-8B3B-F6150FCB82E0> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff50631000 -     0x7fff5067aff7  libsystem_info.dylib (517.30.1) <AB634A98-B8AA-3804-8436-38261FC8EC4D> /usr/lib/system/libsystem_info.dylib
    0x7fff5067b000 -     0x7fff506a1ff7  libsystem_kernel.dylib (4570.61.1) <D7F2010A-EA32-3F62-90DE-85E3C5CC3065> /usr/lib/system/libsystem_kernel.dylib
    0x7fff506a2000 -     0x7fff506edfcb  libsystem_m.dylib (3147.50.1) <8CFB51C9-B422-3379-8552-064C63943A23> /usr/lib/system/libsystem_m.dylib
    0x7fff506ee000 -     0x7fff5070dfff  libsystem_malloc.dylib (140.50.6) <7FD43735-9DDD-300E-8C4A-F909A74BDF49> /usr/lib/system/libsystem_malloc.dylib
    0x7fff5070e000 -     0x7fff5083eff7  libsystem_network.dylib (1229.60.3) <D17B38B7-BE5D-3A9C-9257-F045E7647E8A> /usr/lib/system/libsystem_network.dylib
    0x7fff5083f000 -     0x7fff50849ffb  libsystem_networkextension.dylib (767.60.1) <1745C91F-9AF0-357D-BD40-34451A2D6A5E> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff5084a000 -     0x7fff50853ff3  libsystem_notify.dylib (172) <08012EC0-2CD2-34BE-BF93-E7F56491299A> /usr/lib/system/libsystem_notify.dylib
    0x7fff50854000 -     0x7fff5085bff7  libsystem_platform.dylib (161.50.1) <6355EE2D-5456-3CA8-A227-B96E8F1E2AF8> /usr/lib/system/libsystem_platform.dylib
    0x7fff5085c000 -     0x7fff50867fff  libsystem_pthread.dylib (301.50.1) <0E51CCBA-91F2-34E1-BF2A-FEEFD3D321E4> /usr/lib/system/libsystem_pthread.dylib
    0x7fff50868000 -     0x7fff5086bfff  libsystem_sandbox.dylib (765.60.1) <E5DE4B2F-202D-3474-9F08-7CAB1501D411> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff5086c000 -     0x7fff5086dff3  libsystem_secinit.dylib (30) <DE8D14E8-A276-3FF8-AE13-77F7040F33C1> /usr/lib/system/libsystem_secinit.dylib
    0x7fff5086e000 -     0x7fff50875ff7  libsystem_symptoms.dylib (820.60.2) <9C9E82AB-D1EE-3EC7-B20E-44338CE092AC> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff50876000 -     0x7fff50889fff  libsystem_trace.dylib (829.50.17) <6568D68B-1D4C-38EE-90A9-54821D6403C0> /usr/lib/system/libsystem_trace.dylib
    0x7fff5088b000 -     0x7fff50890ff7  libunwind.dylib (35.3) <BEF3FB49-5604-3B5F-82B5-332B80023AC3> /usr/lib/system/libunwind.dylib
    0x7fff50891000 -     0x7fff508befff  libxpc.dylib (1205.60.9) <16132357-B57A-35F5-B165-487D3F759F45> /usr/lib/system/libxpc.dylib

Model: MacBookPro14,1, BootROM MBP141.0175.B00, 2 processors, Intel Core i5, 2.3 GHz, 8 GB, SMC 2.43f6
Graphics: Intel Iris Plus Graphics 640, Intel Iris Plus Graphics 640, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C3531324D3332443250462D3039
Memory Module: BANK 1/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C3531324D3332443250462D3039
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x170), Broadcom BCM43xx 1.0 (7.77.37.31.1a9)
Bluetooth: Version 6.0.6f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
Thunderbolt Bus: MacBook Pro, Apple Inc., 33.1
